If pdflatex error occurs, sequence breaks

diff --git a/bin/pdflatex_complete_sequence b/bin/pdflatex_complete_sequence
--- a/bin/pdflatex_complete_sequence
+++ b/bin/pdflatex_complete_sequence
@@ -5,7 +5,14 @@ for arg in "$@"; do
     directory=$(dirname $arg)
     argnotex=${arg%.*}
     file=$(basename $argnotex)
-    pdflatex -draftmode $directory/$file
+    nbcompil=1
+    continue_workflow=1
+    pdflatex -draftmode $directory/$file || continue_workflow=0
+    if [[ $continue_workflow == 0 ]]
+    then
+        printf '\n\t' ; printf "PdfLaTeX failed at run $nbcompil.\n\n"
+        break
+    fi
     sleep 0.25
     if [ -e $file.bcf ]
     then
@@ -21,14 +28,19 @@ for arg in "$@"; do
     feynmp_compil &
     wait
     sleep 0.25
-    nbcompil=2
+    ((nbcompil++))
     printf '\n\t' ; printf "PdfLaTeX run $nbcompil...\n\n"
-    pdflatex -interaction=batchmode -halt-on-error $directory/$file
-    while [[ $(grep -l $file.log -e 'Rerun to get cross-references right' -e 'undefined references' -e 'undefined on input line') == $file.log ]] && ((nbcompil < nbcompilmax)); do
+    pdflatex -interaction=batchmode -halt-on-error $directory/$file || continue_workflow=0
+    while [[ $(grep -l $file.log -e 'Rerun to get cross-references right' -e 'undefined references' -e 'undefined on input line') == $file.log ]] && ((nbcompil < nbcompilmax)) && [[ $continue_workflow == 1 ]]; do
         ((nbcompil++))
         printf '\n\t' ; printf "PdfLaTeX run $nbcompil...\n\n"
-        pdflatex -interaction=batchmode -halt-on-error $directory/$file
+        pdflatex -interaction=batchmode -halt-on-error $directory/$file || continue_workflow=0
     done
+    if [[ $continue_workflow == 0 ]]
+    then
+        printf '\n\t' ; printf "PdfLaTeX failed at run $nbcompil.\n\n"
+        break
+    fi
     printf '\n\t' ; printf $nbcompil ; printf ' compilations.\n\n'
     rm -f *.1 *.mp *.t1 &
     rm -f $file.aux $file.out $file.toc $file.lof $file.nav $file.snm $file.synctex.gz $file.maf $file.mtc $file.ptc $file.bcf $file.bbl $file.run.xml $file-blx.bib $file.idx $file.ilg $file.ind &
